import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as Material from '@angular/material';


@NgModule({
  imports: [
    CommonModule,
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatRadioModule,
    Material.MatSelectModule,
    Material.MatCheckboxModule,
    Material.MatDatepickerModule,
    Material.MatNativeDateModule,
    Material.MatButtonModule,
    Material.MatSnackBarModule,
    Material.MatTableModule,
    Material.MatIconModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,
    Material.MatDialogModule,
    Material.MatMenuModule,
    Material.MatToolbarModule,
    Material.MatTooltipModule,
    Material.MatCardModule,
    Material.MatExpansionModule,
    Material.MatStepperModule,
    Material.MatButtonToggleModule,
    Material.MatSliderModule,
    Material.MatChipsModule,
  ],
  exports: [
    Material.MatToolbarModule,
    Material.MatGridListModule,
    Material.MatFormFieldModule,
    Material.MatInputModule,
    Material.MatRadioModule,
    Material.MatSelectModule,
    Material.MatCheckboxModule,
    Material.MatDatepickerModule,
    Material.MatNativeDateModule,
    Material.MatButtonModule,
    Material.MatSnackBarModule,
    Material.MatTableModule,
    Material.MatIconModule,
    Material.MatPaginatorModule,
    Material.MatSortModule,
    Material.MatDialogModule,
    Material.MatMenuModule,
    Material.MatToolbarModule,
    Material.MatTooltipModule,
    Material.MatCardModule,
    Material.MatExpansionModule,
    Material.MatStepperModule,
    Material.MatButtonToggleModule,
    Material.MatSliderModule,
    Material.MatChipsModule,
    Material.MatAutocompleteModule
  ],
  declarations: []
})
export class MaterialModule { }
